### ISSUE TITLE
File 'nil' does not exist when calling jedi from elisp

### ISSUE THREAD

**Issue by nayefc** [tkf/emacs-jedi#224]
In some cases, I keep getting `File 'nil' does not exist` when calling Jedi from Elisp.

This seems to hit this: https://github.com/tkf/emacs-jedi/blob/d0f6ea485f7f8575f85b97d61f662bcf88411047/jedi-core.el#L788

My code:
```elisp
(jedi:goto-definition 1 `definition))
```

Or even:
```elisp
(jedi:goto-definition nil `definition))
```

I am writing wrappers to jump to the function definitions directly. Here they are:

```elisp
(defun jedi:goto-definition-same-frame ()
"Jedi goto-definition wrapper to go to definition directly."
  (interactive)
  (jedi:goto-definition nil `definition))

(defun jedi:goto-definition-new-frame ()
  "Jedi goto-definition wrapper in a new, nexts frame."
  (interactive)
  (jedi:goto-definition 1 `definition))
```

Any idea what is wrong with them?

**Comment by braham-snyder** [comment]
I'm still seeing this error on builtins -- it looks like we should instead be getting "Cannot see the definition of __builtin__." (but `module_name` is in fact `nil`, not `"__builtin__"`)? (Due to https://github.com/tkf/emacs-jedi/issues/265 I suppose.)

If that's correct, perhaps this issue should be re-opened to fix the error message?
