### ISSUE TITLE
jedi:goto-definition does not work with namespace packages.

### ISSUE THREAD

**Issue by mattdeboard** [tkf/emacs-jedi#256]
It is as the subject says. `jedi:goto-definition` fails when searching for [namespace packages](https://pythonhosted.org/setuptools/setuptools.html#namespace-packages) ([PEP 420](https://www.python.org/dev/peps/pep-0420/)), such as [dogpile.cache](https://bitbucket.org/zzzeek/dogpile.cache).

Running `jedi:goto-definition` on a line like `from dogpile.cache import make_region` will fail with "Definition not found." 

I have noticed that IPython also will not autocomplete for such packages.

The surface-level reason this doesn't work is because there is no `site-packages/dogpile/__init__.py`. If I manually add that file, then `jedi:goto-definition` works just fine.

**Comment by jguenther** [comment]
@mattdeboard The way that I have solved similar problems with ImportErrors for namespaced python packages is to use `site.addsitedir()` instead of `sys.path.append()`. This adds the dir to `sys.path` and marks the dir as a site-packages dir, which means that the `.pth` files in that dir will be processed. `.pth` files are used by namespace packages to make them import correctly, and they won't be processed unless they're installed into a site-packages dir.

I think that changing `jediepcserver`'s treatment of `--sys-path` arguments to call `site.addsitedir` instead of just adding the dir to `sys.path` might solve this. I might try making a PR over the holidays to try that out, as I keep running into this problem.

**Comment by syohex** [comment]
Sorry very too late response. Could you show us code which reproduce this issue ?

**Comment by syohex** [comment]
```python
from dogpile.cache import make_region
```

I can go to definition when cursor is on `make_region`.

Please reopen the issue, if you still have this issue.
