### ISSUE TITLE
jedi:goto-definition should push current point onto mark ring for easy return

### ISSUE THREAD

**Issue by ryanolf** [tkf/emacs-jedi#26]
I'm loving emacs-jedi, and find myself using jedi:goto-definition (C-.) a lot. However, this function would be even more convenient if it allowed me to return easily to the place where I called it in the first place (via C-u C-SPC). This can be accomplished by setting the mark before jumping to the definition.

**Comment by spookylukey** [comment]
This appears to not work again - after a `jedi:goto-definition`, doing `C-u C-SPC` or `pop-to-mark-command` doesn't get me back to where I was.

I can use `C-c ,` or `jedi:goto-definition-pop-marker` to get back to where I was. But I just want to do "go back to where I was", and use my normal keyboard shortcut that does that, rather than remember "the last thing I did to get here was a goto-definition, therefore I have to use this different keyboard shortcut to reverse it".

Can this be re-opened, or should I open a new ticket?

**Comment by immerrr** [comment]
@spookylukey that is the idea, to use `jedi:goto-definition-pop-marker`.

The change to separate jedi marker ring was intentional. Incidentally, it was me who requested it in #42 and implemented it in #44. It was 6 years ago, so my memory is quite foggy, but IIRC it was about the fact that `pop-mark` only worked well for same-buffer marks and to go back to a different buffer you needed to do some mental tracking about when to use `pop-global-mark` instead. Or so says my summary of the issue:

> The problem is that you'd want a global mark so as to be able to jump back across buffers, but push-mark alters global-mark-ring only if the previous push-mark was from a different buffer. Basically, you need to mentally track where did you start your lookup: if goto-definition resulted in a location in different buffer, you need to do global-pop-mark to go back, if not, you need to use buffer-local mark-ring with pop-to-mark-command. This is quite inconvenient. 

If you know a way around cross-buffer navigation via the traditional mark that does not require you to do mental tracking of navigation history, let's discuss it in a separate issue.

**Comment by immerrr** [comment]
Btw, in my config I keep jedi bindings close to `xref` ones, so I have `jedi:goto-definition` and `jedi:goto-definition-pop-marker`  on `M-.` and `M-,` respectively, same as the default bindings for `xref-find-definitions` and `xref-pop-marker-stack` that I use in modes that support `xref`.

**Comment by spookylukey** [comment]
You're right, having tried this, being able to pop across buffers is much nicer than what I was even attempting to do before. I can retrain my fingers with this. :+1:
