### ISSUE TITLE
Remove git submodule sphinx-eldomain 

### ISSUE THREAD

**Issue by eflanigan00** [tkf/emacs-jedi#289]
Please make this a dependency of the project instead of a git submodule.

**Comment by ramnes** [comment]
Or at least, please use the HTTPS URL, so that it can be pulled from anywhere.

**Comment by fmichaut-dev** [comment]
I was having errors to clone or update this submodule, because it is using the deprecated `git://` url format, had to change it in the `.git/config` file.
Could you update the URL to avoid this error in the future ?
![image](https://user-images.githubusercontent.com/33881730/158626867-7f7f84ef-1f93-4bdf-8db9-c9595636eab0.png)

**Comment by immerrr** [comment]
This should be fixed with 292119da8bea526ba370b80e57b0510d58b76ae4.

**Comment by ramnes** [comment]
Thank you for reviving emacs-jedi!
